STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS:
  - Bf:
    Min: 5.0
    Max: 30.0
  - Cf:
    Min: 0.5
    Max: 2.0
  - Df:
    Min: 100.0
    Max: 10000.0
  - Ef:
    Min: -2.0
    Max: 0.0
  - Br:
    Min: 5.0
    Max: 30.0
  - Cr:
    Min: 0.5
    Max: 2.0
  - Dr:
    Min: 100.0
    Max: 10000.0
  - Er:
    Min: -2.0
    Max: 0.0
  - Cm1:
    Min: 100.0
    Max: 10000.0  
  - Cm2:
    Min: 0.0
    Max: 1.0
  - Cr0:
    Min: 0.1
    Max: 1.4
  - Cr2:
    Min: 0.1
    Max: 1.0
  - Iz: 
    Min: 500.0
    Max: 2000.0
  - Shf:
    Min: -0.02
    Max: 0.02
  - Svf: 
    Min: -300.0
    Max: 300.0
  - Shr:
    Min: -0.02
    Max: 0.02
  - Svr:
    Min: -300.0
    Max: 300.0
VEHICLE_SPECS:
  lf: 1.248
  lr: 1.7328
  mass: 790.0
MODEL:
  NAME: DeepDynamicsIAC
  HORIZON: 15
  LAYERS:
    - DENSE:
      OUT_FEATURES: 225
      ACTIVATION: Tanh
      # LAYERS: 3
    - DENSE:
      OUT_FEATURES: 188
      ACTIVATION: Tanh
    - DENSE:
      OUT_FEATURES: 188
      ACTIVATION: Tanh
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 208
    NUM_EPOCHS: 400
    OPTIMIZER: Adam
    LR: 0.001
